# -*- coding: utf-8 -*-
"""dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JltZqKUXAfFvy8SxYpl_XxFrO0mfUR9y
"""

#Load your data (reuse the same SQL queries from Part A, or load your query results as DataFrames)
!pip install streamlit
import streamlit as st
import pandas as pd
import sqlite3

# -----------------------------
# Page Configuration
# -----------------------------
st.set_page_config(
    page_title="NextGenLearners Dashboard",
    page_icon="📊",
    layout="wide"
)

st.title("📊 NextGenLearners Program Performance Dashboard")

# -----------------------------
# Load Database
conn = sqlite3.connect('nextgen.db')
applicants = pd.read_sql("SELECT * FROM applicants;", conn)
interns = pd.read_sql("SELECT * FROM interns;", conn)
scores = pd.read_sql("SELECT * FROM hackathon_scores;", conn)

#Add a domain filter (the "interactive" requirement):
domain_list = ['All'] + sorted(applicants['domain'].unique().tolist())
selected_domain = st.selectbox('Filter by Domain', domain_list)

# -----------------------------
# Filter Data
# -----------------------------
if selected_domain != 'All':
  applicants_filtered = applicants[applicants['domain'] == selected_domain]
else:
  applicants_filtered = applicants

st.subheader("Program Funnel")

col1, col2 = st.columns(2)

with col1:
  st.metric("Total Applicants", len(applicants_filtered))

with col2:
    completed = len(interns[interns["completion_status"] == "Completed"])

    st.metric("Completed Interns", completed)

# Completion Rate per Domain (Reuse Query 4)
st.subheader("Completion Rate per Domain")

query4 = """
SELECT
    a.domain,
    COUNT(DISTINCT a.applicant_id) AS total_applicants,
    COUNT(DISTINCT i.intern_id) AS total_completed,
    ROUND(
        100.0 * COUNT(DISTINCT i.intern_id) /
        COUNT(DISTINCT a.applicant_id), 2
    ) AS conversion_rate_pct
FROM applicants a
LEFT JOIN interns i
ON a.applicant_id = i.applicant_id
AND i.completion_status = 'Completed'
GROUP BY a.domain
ORDER BY conversion_rate_pct DESC;
"""

conversion = pd.read_sql(query4, conn)

st.bar_chart(
    conversion.set_index("domain")["conversion_rate_pct"]
)

#Average Hackathon Score per Domain (Reuse Query 2)
st.subheader("Average Hackathon Score per Domain")

query2 = """
SELECT
    domain,
    ROUND(AVG(score),2) AS avg_score
FROM hackathon_scores
GROUP BY domain
ORDER BY avg_score DESC;
"""

avg_score = pd.read_sql(query2, conn)

st.bar_chart(
    avg_score.set_index("domain")["avg_score"]
)

st.subheader("Top 10 Performers")

query3 = """
SELECT
    i.intern_id,
    a.name,
    i.domain,
    h.score
FROM interns i
JOIN applicants a
ON i.applicant_id = a.applicant_id
JOIN hackathon_scores h
ON i.intern_id = h.intern_id
ORDER BY h.score DESC
LIMIT 10;
"""

leaderboard = pd.read_sql(query3, conn)

st.dataframe(leaderboard)